apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: image=ayushpan19/sample-app
    argocd-image-updater.argoproj.io/image.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
spec:
  project: default
  source:
    repoURL: https://github.com/Ayush-pd07/argocd-helm-demo.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
